### ISSUE TITLE
ingress-nginx related images broken

### ISSUE THREAD

**Issue by xchan** [nwcdlabs/container-mirror#182]
$ docker pull 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/google_containers/ingress-nginx/controller:v1.2.1@sha256:5516d103a9c2ecc4f026efbd4b40662ce22dc1f824fb129ed121460aaa5c47f8
048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/google_containers/ingress-nginx/controller@sha256:5516d103a9c2ecc4f026efbd4b40662ce22dc1f824fb129ed121460aaa5c47f8: Pulling from gcr/google_containers/ingress-nginx/controller
455c02918c45: Pulling fs layer
def20be812d2: Pulling fs layer
ce5661884629: Pulling fs layer
678e424763a4: Waiting
7ead3e106685: Waiting
cd244451095b: Waiting
4f4fb700ef54: Waiting
f6ea01d28a17: Waiting
d3be42a364a9: Waiting
041e9420e258: Waiting
4bc068c20ea4: Waiting
b97555290c31: Waiting
8e7e86f147ef: Waiting
58079bced8cb: Waiting
6d2419008fa9: Waiting
error pulling image configuration: download failed after attempts=1: unknown blob

**Comment by toreydai** [comment]
Please submit a pull request.
