### ISSUE TITLE
pull image error - docker login required

### ISSUE THREAD

**Issue by shengbo66** [nwcdlabs/container-mirror#3]
When I try to pull the image follow the example from EC2 in ZHY, it fails.
image: k8s.gcr.io/coredns:1.3.1

error message as blow.
_6m9s        Warning   Failed              pod/test-dcf996db6-5f855                     Failed to pull image "048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/google-containers/coredns:1.3.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/google-containers/coredns, repository does not exist or may require 'docker login'_

**Comment by nowfox** [comment]
According to [mapping rules](https://github.com/nwcdlabs/container-mirror#amazon-ecr%E9%95%9C%E5%83%8F%E8%B7%AF%E5%BE%84),the URI is 
048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/google_containers/coredns:1.3.1
