### ISSUE TITLE
mirror gcr.io/google-containers ?

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/container-mirror#30]
gcr.io google-containers裡面有481個public container images，每個image有各自不同數量的tags，如果可以全部mirror回來應該可以節省很多後面遇到的問題。

我想先開一個issue，大家可以討論看看是否有這個需求，使用場景是什麼，歡迎comments

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL

**Comment by zxkane** [comment]
gcp 提供了工具查询 gcr-container 内所有的镜像

https://stackoverflow.com/a/44298851/390513

**Comment by zxkane** [comment]
A complete [images list](https://github.com/nwcdlabs/container-mirror/files/4631889/gcr-containers-images.txt) of `gcr.io/gcr-containers` was dumped by [a simple script](https://gist.github.com/zxkane/bd2bed189e65b63e56fb028019839744).

**Comment by nowfox** [comment]
目前https://github.com/nwcdlabs/container-mirror/files/4631889/gcr-containers-images.txt清单中的已拉取完毕
