### ISSUE TITLE
No cvallance/mongo-k8s-sidecar mirror  

### ISSUE THREAD

**Issue by yuantianchi** [nwcdlabs/container-mirror#56]
hope to add cvallance/mongo-k8s-sidecar mirror 

  Warning  Failed                  13m (x6 over 14m)     kubelet, ip-10-20-193-142.cn-northwest-1.compute.internal  Error: ImagePullBackOff
  Normal   Pulling                 13m (x4 over 14m)     kubelet, ip-10-20-193-142.cn-northwest-1.compute.internal  Pulling image "048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/cvallance/mongo-k8s-sidecar"

**Comment by nowfox** [comment]
请参考 [增加新的容器镜像](https://github.com/nwcdlabs/container-mirror#%E5%A2%9E%E5%8A%A0%E6%96%B0%E7%9A%84%E5%AE%B9%E5%99%A8%E9%95%9C%E5%83%8F)，提交PR
