### ISSUE TITLE
Add images to mirror

### ISSUE THREAD

**Issue by atlan14** [nwcdlabs/container-mirror#60]
could you please add the following images to the mirror:

quay.io/digital_ecosystems/kubernetes-agent:1.3.0
quay.io/digital_ecosystems/mendix-operator:1.4.0
quay.io/digital_ecosystems/mx-m2ee-sidecar:1.3.0
quay.io/digital_ecosystems/mx-m2ee-metrics:1.1.0
quay.io/digital_ecosystems/image-builder:ingvar-rhel

**Comment by nowfox** [comment]
请参考[如何增加新的容器镜像](https://github.com/nwcdlabs/container-mirror/blob/master/docs/how-to-request-new-container-image.md)提交PR。提交时说明镜像的功能，如果有blog引用更佳，便于复核。

**Comment by atlan14** [comment]
好的 
https://github.com/nwcdlabs/container-mirror/pull/61
