### ISSUE TITLE
Please add quay.io/bitnami/sealed-secrets-controller in mirrored container

### ISSUE THREAD

**Issue by OffCode** [nwcdlabs/container-mirror#64]
we have to use sealed secrets in our project in TSP Cloud at AWS China. 
This is the link to the Helm Chart for further information, just in case: 
https://github.com/helm/charts/tree/master/stable/sealed-secrets

The image is not mirrored yet and the Pod failed in ImagePullBackOff state: 
```shell
 Warning  Failed     16m (x4 over 17m)     kubelet, ip-<SUPPRESSED>.cn-north-1.compute.internal  Failed to pull image "048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/bitnami/sealed-secrets-controller:v0.12.4": rpc error: code = Unknown desc = Error response from daemon: manifest for 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/bitnami/sealed-secrets-controller:v0.12.4 not found: manifest unknown: Requested image not found
```

Thank you in advance for a quick action

**Comment by nowfox** [comment]
请参考[如何增加新的容器镜像](https://github.com/nwcdlabs/container-mirror/blob/master/docs/how-to-request-new-container-image.md)提交PR。提交时说明镜像的功能，如果有blog引用更佳，便于复核。

**Comment by OffCode** [comment]
@nowfox Please kindly write you comments in english. Unluckily I can't understand Chinese language

**Comment by nowfox** [comment]
I've seen your PR.I have merged this PR.  
quay.io/bitnami/sealed-secrets-controller:v0.12.4 is OK.
