### ISSUE TITLE
Add fluent/fluentd-kubernetes-daemonset:v1.1-debian-elasticsearch

### ISSUE THREAD

**Issue by OffCode** [nwcdlabs/container-mirror#66]
We have a fluentd deamonset as log scraper to push our log entries into an ElasticSearch cluster.
For this purpose we use the following specialized/pre-configured docker image:
fluent/fluentd-kubernetes-daemonset:v1.1-debian-elasticsearch

Let us add this docker image to the mirrored images.

**Comment by nowfox** [comment]
Your PR is fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch,Not fluent/fluentd-kubernetes-daemonset:v1.1-debian-elasticsearch.Please confirm.
fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch is done.

**Comment by OffCode** [comment]
@nowfox Thank you very much for your quick action!
