### ISSUE TITLE
麻烦支持 v1.19.0

### ISSUE THREAD

**Issue by SecretSun** [nwcdlabs/container-mirror#69]
Image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.19.0

**Comment by nowfox** [comment]
请参考[如何增加新的容器镜像](https://github.com/nwcdlabs/container-mirror/blob/master/docs/how-to-request-new-container-image.md)提交Pull request。

**Comment by SecretSun** [comment]
感谢
