### ISSUE TITLE
Kops集群需要的VM AMI镜像在AWS全球有，但在AWS 中国北京和宁夏都没有

### ISSUE THREAD

**Issue by max1314** [nwcdlabs/container-mirror#74]
kubernetes 1.16, 1.17, 1.18 使用kops更新的时候需要对应的AMI列表：
```   
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.17.0 <1.18.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
      providerID: aws
      kubernetesVersion: ">=1.18.0"
```
相关链接：
https://github.com/kubernetes/kops/blob/master/channels/stable#L47-L49
镜像AMI在aws 全球个region的id：
https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch

**Comment by nowfox** [comment]
该问题是AMI复制问题，不在本项目范围内。  
该需求可实现，可自行从全球复制AMI到中国区域。  
如果需要帮助，请登录AWS控制台后，在`支持控制面板`创建新案例（case），类别需要为`技术支持`。

**Comment by max1314** [comment]
@nowfox 已经创建了，CaseID 为1460969824
