### ISSUE TITLE
镜像地址

### ISSUE THREAD

**Issue by kakawinwin** [nwcdlabs/container-mirror#97]
请问新拉取的镜像，下面的地址正确吗？
048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/arrikto/jupyter-kale:v0.5.0-47-g2427cc9
048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/arrikto/rok-tools:l0-release-v1.0-rc6

**Comment by nowfox** [comment]
arrikto/jupyter-kale你在Pull request里写的tag是4a5d7e63-9f74f267，因此这个对应的地址是048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/arrikto/jupyter-kale:4a5d7e63-9f74f267，如果需要arrikto/jupyter-kale:v0.5.0-47-g2427cc9，请重新提起pull request。
048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/arrikto/rok-tools:l0-release-v1.0-rc6这个是对的

**Comment by kakawinwin** [comment]
收到，谢谢
